### ISSUE TITLE
Nice to have: Possible combinations count in README

### ISSUE THREAD

**Issue by theresnotime** [theresnotime/as-a-treat#29]
**As a** odd little fox, **I would like** the current possible combinations count (e.g. output of `gen.py -c`) to be reflected in the README, **so that** number go up.

I'm guessing this would either need to be a pre-commit hook, or updated via the GH actions.

**Comment by crmsnbleyd** [comment]
I could add it as a git hook, but that would need all the required packages to be present, as well as a config.py file.

**Comment by theresnotime** [comment]
It'll update [the bio instead](https://fox.nexus/@treats) :)
